name: flutter_bloc_with_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # state management
  flutter_bloc: ^8.1.2

  # comparing data objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.6.0

  # date format
  intl: ^0.19.0

  # database
  floor: ^1.4.2

  # make request to api
  retrofit: ^4.1.0

  # hooks
  flutter_hooks: ^0.20.5

  # cached image
  cached_network_image: ^3.2.0
  dio: ^5.5.0+1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: 8.1.2
  floor_generator: 1.5.0
  build_runner: 2.4.11

flutter:

  uses-material-design: true